// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4QfO5F_0yBhe08AzOh3xbaOvsXon9EM',
    appId: '1:445160326884:web:f8c90e05a076fff1e54ef1',
    messagingSenderId: '445160326884',
    projectId: 'tic-tac-toe-cse464',
    authDomain: 'tic-tac-toe-cse464.firebaseapp.com',
    storageBucket: 'tic-tac-toe-cse464.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVedkUWHxeROz3WHWfi3L9CC6c1OS1zFc',
    appId: '1:445160326884:android:ee572adbe077103ce54ef1',
    messagingSenderId: '445160326884',
    projectId: 'tic-tac-toe-cse464',
    storageBucket: 'tic-tac-toe-cse464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DrSXhC0bVSjvAkIAYHwfQShRoEqlzzU',
    appId: '1:445160326884:ios:803c24b86ccc4b97e54ef1',
    messagingSenderId: '445160326884',
    projectId: 'tic-tac-toe-cse464',
    storageBucket: 'tic-tac-toe-cse464.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToeApp',
  );
}