// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGnuCtppE3AuC38-hSyyKm89R9pFA_zY',
    appId: '1:317486815772:web:9c1ded3cfa9a0e2e951dd9',
    messagingSenderId: '317486815772',
    projectId: 'tic-tac-toe-group-9e01f',
    authDomain: 'tic-tac-toe-group-9e01f.firebaseapp.com',
    storageBucket: 'tic-tac-toe-group-9e01f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUuew23wkZZY_peY2hEIQkYuHoyehXJU',
    appId: '1:317486815772:android:2eefed0c8d67d64f951dd9',
    messagingSenderId: '317486815772',
    projectId: 'tic-tac-toe-group-9e01f',
    storageBucket: 'tic-tac-toe-group-9e01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSrlLC4XRaJxazrIiHsk6aKx5bQ87K5g',
    appId: '1:317486815772:ios:4f0361bad27d6dc1951dd9',
    messagingSenderId: '317486815772',
    projectId: 'tic-tac-toe-group-9e01f',
    storageBucket: 'tic-tac-toe-group-9e01f.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgSrlLC4XRaJxazrIiHsk6aKx5bQ87K5g',
    appId: '1:317486815772:ios:4f0361bad27d6dc1951dd9',
    messagingSenderId: '317486815772',
    projectId: 'tic-tac-toe-group-9e01f',
    storageBucket: 'tic-tac-toe-group-9e01f.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmGnuCtppE3AuC38-hSyyKm89R9pFA_zY',
    appId: '1:317486815772:web:4b1ed4af430ca850951dd9',
    messagingSenderId: '317486815772',
    projectId: 'tic-tac-toe-group-9e01f',
    authDomain: 'tic-tac-toe-group-9e01f.firebaseapp.com',
    storageBucket: 'tic-tac-toe-group-9e01f.firebasestorage.app',
  );
}
